// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/masnann/plant_care/features/plant/domain"
	mock "github.com/stretchr/testify/mock"
)

// ServicePlantInterface is an autogenerated mock type for the ServicePlantInterface type
type ServicePlantInterface struct {
	mock.Mock
}

// CountPlants provides a mock function with given fields: userID
func (_m *ServicePlantInterface) CountPlants(userID uint64) (uint64, error) {
	ret := _m.Called(userID)

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePlants provides a mock function with given fields: plantID
func (_m *ServicePlantInterface) DeletePlants(plantID uint64) error {
	ret := _m.Called(plantID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(plantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPlantsByID provides a mock function with given fields: plantID
func (_m *ServicePlantInterface) GetPlantsByID(plantID uint) (*domain.PlantModel, error) {
	ret := _m.Called(plantID)

	var r0 *domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*domain.PlantModel, error)); ok {
		return rf(plantID)
	}
	if rf, ok := ret.Get(0).(func(uint) *domain.PlantModel); ok {
		r0 = rf(plantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(plantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlantsByUserID provides a mock function with given fields: userID
func (_m *ServicePlantInterface) GetPlantsByUserID(userID uint64) ([]*domain.PlantModel, error) {
	ret := _m.Called(userID)

	var r0 []*domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*domain.PlantModel, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*domain.PlantModel); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPlantsWithPagination provides a mock function with given fields: userID, offset, pageSize
func (_m *ServicePlantInterface) GetPlantsWithPagination(userID uint64, offset int, pageSize int) ([]*domain.PlantModel, error) {
	ret := _m.Called(userID, offset, pageSize)

	var r0 []*domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, int, int) ([]*domain.PlantModel, error)); ok {
		return rf(userID, offset, pageSize)
	}
	if rf, ok := ret.Get(0).(func(uint64, int, int) []*domain.PlantModel); ok {
		r0 = rf(userID, offset, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, int, int) error); ok {
		r1 = rf(userID, offset, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPlants provides a mock function with given fields: _a0
func (_m *ServicePlantInterface) InsertPlants(_a0 *domain.PlantModel) (*domain.PlantModel, error) {
	ret := _m.Called(_a0)

	var r0 *domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.PlantModel) (*domain.PlantModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*domain.PlantModel) *domain.PlantModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.PlantModel) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPlantsByName provides a mock function with given fields: name
func (_m *ServicePlantInterface) SearchPlantsByName(name string) ([]*domain.PlantModel, error) {
	ret := _m.Called(name)

	var r0 []*domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.PlantModel, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.PlantModel); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchPlantsByType provides a mock function with given fields: types
func (_m *ServicePlantInterface) SearchPlantsByType(types string) ([]*domain.PlantModel, error) {
	ret := _m.Called(types)

	var r0 []*domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.PlantModel, error)); ok {
		return rf(types)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.PlantModel); ok {
		r0 = rf(types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(types)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePlants provides a mock function with given fields: _a0
func (_m *ServicePlantInterface) UpdatePlants(_a0 *domain.PlantModel) (*domain.PlantModel, error) {
	ret := _m.Called(_a0)

	var r0 *domain.PlantModel
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.PlantModel) (*domain.PlantModel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*domain.PlantModel) *domain.PlantModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PlantModel)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.PlantModel) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServicePlantInterface creates a new instance of ServicePlantInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicePlantInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicePlantInterface {
	mock := &ServicePlantInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
